<?php

namespace CoreBundle\Repository;

/**
 * AccessTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
