<?php

namespace CoreBundle\Repository;

/**
 * BillingPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
